const logger = require('../utils/logger');

/**
 * Handle direct file upload to local server
 * Note: Middleware (uploadLocal + validateFileContent) MUST be applied in the route.
 */
const localUpload = async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: 'No file uploaded or file rejected by security policy' });
        }

        // Generate public URL
        const protocol = req.protocol;
        const host = req.get('host');
        
        // Use req.file.filename (generated by UUID in middleware)
        const publicUrl = `${protocol}://${host}/public/uploads/${req.file.filename}`;

        logger.info('UPLOAD', `File uploaded locally by user ${req.userId}`, { 
            filename: req.file.filename,
            size: req.file.size,
            verifiedMimeType: req.file.verifiedMimeType
        });

        res.json({
            success: true,
            data: {
                publicUrl: publicUrl,
                filename: req.file.filename,
                mimetype: req.file.verifiedMimeType || req.file.mimetype
            }
        });
    } catch (error) {
        logger.error('UPLOAD', 'Local upload failure:', error);
        res.status(500).json({ error: 'Failed to upload file', message: error.message });
    }
};

/**
 * Handle file upload to S3
 */
const s3Upload = async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: 'No file uploaded or file rejected by security policy' });
        }

        logger.info('UPLOAD', `File uploaded to S3 by user ${req.userId}`, { 
            location: req.file.location,
            key: req.file.key,
            size: req.file.size
        });

        res.json({
            success: true,
            data: {
                publicUrl: req.file.location, // multer-s3 provides 'location' as the public URL
                key: req.file.key,
                filename: req.file.originalname,
                mimetype: req.file.mimetype,
                size: req.file.size
            }
        });
    } catch (error) {
        logger.error('UPLOAD', 'S3 upload failure:', error);
        res.status(500).json({ error: 'Failed to upload file to S3', message: error.message });
    }
};

module.exports = { 
    localUpload,
    s3Upload
};
